blank_issues_enabled: yes

contact_links:
  - name: Discussion Forum
    url: https://forums.swift.org/c/development/swift-docc
    about: Ask and answer questions about Swift-DocC and authoring documentation
  - name: Swift-DocC Documentation
    url: https://www.swift.org/documentation/docc/
    about: Learn about how to use Swift-DocC for authoring documentation
